config/routes.rb
Picturesque::Application.routes.draw do
  resources :spot_finders

  root :to => "spots#index"

  resources :spots
  resources :paintings do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :painting
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name
  has_many :paintings
end





#<div id="paintings">
#  <% for painting in @gallery.paintings %>
#    <div class="painting">
#      <%= image_tag painting.image_url if painting.image? %>
#      <div class="name"><%= painting.name %></div>
#      <div class="actions">
#        <%= link_to "edit", edit_painting_path(painting) %> |
#        <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
#      </div>
#    </div>
#  <% end %>
#  <div class="clear"></div>
#</div>

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :spot_id, :name, :image, :remote_image_url, :description
  belongs_to :spot
  mount_uploader :image, ImageUploader
  has_many :comments, :dependent => :destroy
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  attr_accessible :name, :latitude, :longitude
  has_many :paintings
end





#<div id="paintings">
#  <% for painting in @gallery.paintings %>
#    <div class="painting">
#      <%= image_tag painting.image_url if painting.image? %>
#      <div class="name"><%= painting.name %></div>
#      <div class="actions">
#        <%= link_to "edit", edit_painting_path(painting) %> |
#        <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
#      </div>
#    </div>
#  <% end %>
#  <div class="clear"></div>
#</div>

app/models/spot_finder.rb
class SpotFinder < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
      @painting = Painting.find(params[:painting_id])
      @comment = @painting.comments.create(params[:comment])
      redirect_to painting_path(@painting)
    end

    def destroy
      @painting = Painting.find(params[:painting_id])
      @comment = @painting.comments.find(params[:id])
      @comment.destroy
      redirect_to painting_path(@painting)
    end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def new
    @painting = Painting.new(:spot_id => params[:spot_id])
  end

  def create
    @painting = Painting.new(params[:painting])
    if @painting.save
      flash[:notice] = "Successfully created painting."
      redirect_to @painting.spot
    else
      render :action => 'new'
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      flash[:notice] = "Successfully updated painting."
      redirect_to @painting.spot
    else
      render :action => 'edit'
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    flash[:notice] = "Successfully destroyed painting."
    redirect_to @painting.spot
  end
end

app/controllers/spot_finders_controller.rb
class SpotFindersController < ApplicationController
  # GET /spot_finders
  # GET /spot_finders.xml
  def index
    @spot_finders = SpotFinder.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @spot_finders }
    end
  end

  # GET /spot_finders/1
  # GET /spot_finders/1.xml
  def show
    @spot_finder = SpotFinder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @spot_finder }
    end
  end

  # GET /spot_finders/new
  # GET /spot_finders/new.xml
  def new
    @spot_finder = SpotFinder.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @spot_finder }
    end
  end

  # GET /spot_finders/1/edit
  def edit
    @spot_finder = SpotFinder.find(params[:id])
  end

  # POST /spot_finders
  # POST /spot_finders.xml
  def create
    @spot_finder = SpotFinder.new(params[:spot_finder])
    name = @spot_finder.name
    longitude = @spot_finder.longitude
    latitude = @spot_finder.latitude

    respond_to do |format|
      if @spot_finder.save
        format.html { redirect_to(@spot_finder, :notice => 'Spot finder successfully found a result.') }
        format.xml  { render :xml => @spot_finder, :status => :created, :location => @spot_finder }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @spot_finder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /spot_finders/1
  # PUT /spot_finders/1.xml
  def update
    @spot_finder = SpotFinder.find(params[:id])

    respond_to do |format|
      if @spot_finder.update_attributes(params[:spot_finder])
        format.html { redirect_to(@spot_finder, :notice => 'Spot finder was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @spot_finder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /spot_finders/1
  # DELETE /spot_finders/1.xml
  def destroy
    @spot_finder = SpotFinder.find(params[:id])
    @spot_finder.destroy

    respond_to do |format|
      format.html { redirect_to(spot_finders_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    @spots  = Spot.all
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(params[:spot])
    if @spot.save
      flash[:notice] = "Successfully created spot."
      redirect_to @spot
    else
      render :action => 'new'
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update_attributes(params[:spot])
      flash[:notice] = "Successfully updated spot."
      redirect_to spot_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    flash[:notice] = "Successfully destroyed spot."
    redirect_to spots_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/spot_finders_helper.rb
module SpotFindersHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/comments/_comment.html.erb
<p>
  <b> <%= comment.commenter %></p> </b>
<p>
  <%= comment.body %>
  <%= link_to 'Delete',[comment.painting, comment],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>

<br>

app/views/comments/_form.html.erb
<%= form_for([@painting, @painting.comments.build]) do |f| %>
    <div class="field">
      <%= f.label :commenter %><br />
      <%= f.text_field :commenter %>
    </div>

    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/comments/show.html.erb
<% title "Description" %>

<% @painting = Painting.find(params[:id]) %>



<p id="notice"><%= notice %></p>

<div class= "show">
  <h2 style="text-align:center;position:absolute;width:inherit;">File</h2>
  <div class= "show-heading">
  <%= link_to image_tag('home.png', :size=>'32x32'), root_path, :class=>"button"%>
  <%= link_to image_tag('close.png', :size=>'32x32'), @painting, :class=>"button", :confirm => 'Are you sure?', :method => :delete %>
  </div>

<div class="icon">
  <%= image_tag(@painting.image_url, :size=> "180x180") %>
  <p><b><%= @painting.name %></b></p>
</div>

<div class="side">
<p>
  <b>Name:</b>
  <%= @painting.name%>
<p>
<p>
  <b>Description</b>
  <%= @painting.description%>
<p>

<p>
  <%= link_to 'Download', @painting.image_url%>
<p>


<p>
  <%= link_to "Edit this File", edit_painting_path(@painting) %>  
</p>

</div>
</div>
<br />


<div class= "show">
  <h2 style="text-align:center;position:relative;width:inherit;">Comments</h2>
  <div class="body">
  <%= render :partial => "comments/comment",
             :collection => @painting.comments %>
  <br>
  <h2>Add a comment</h2>
    <%= render "comments/form" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Spot" %></title>
    
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>

    <%= stylesheet_link_tag :all %>
   <script language="JavaScript" type="text/javascript" src="/Javascripts/ContentFlow/contentflow.js"></script>

  </head>
  <body>
    <div id="container" class="center" >
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/paintings/_form.html.erb
<%= form_for @painting, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :spot_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/paintings/edit.html.erb
<% title "Edit Painting" %>

<%= render 'form' %>

<p><%= link_to "Back to Spot", @painting.spot %></p>

app/views/paintings/new.html.erb
<% title "New File" %>

<%= render 'form' %>

<p><%= link_to "Back to Spot", @painting.spot %></p>

app/views/paintings/show.html.erb
<% title "Description" %>

<% @painting = Painting.find(params[:id]) %>



<p id="notice"><%= notice %></p>

<div class= "show">
  <h2 style="text-align:center;position:absolute;width:inherit;">Photo Information</h2>
  <div class= "show-heading">
  <%= link_to image_tag('home.png', :size=>'32x32'), root_path, :class=>"button"%>
  <%= link_to image_tag('close.png', :size=>'32x32'), @painting, :class=>"button", :confirm => 'Are you sure?', :method => :delete %>
  </div>

<div class="icon">
  <%= image_tag(@painting.image_url, :size=> "180x180") %>
  <p><b><%= @painting.name %></b></p>
</div>

<div class="side">
<p>
  <b>Name:</b>
  <%= @painting.name%>
<p>
<p>
  <b>Description</b>
  <%= @painting.description%>
<p>

<p>
  <%= link_to "Edit this Painting", edit_painting_path(@painting) %>  
</p>


</div>
</div>
<br />

app/views/spot_finders/_form.html.erb
<%= form_for(@spot_finder) do |f| %>
  <% if @spot_finder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot_finder.errors.count, "error") %> prohibited this spot_finder from being saved:</h2>

      <ul>
      <% @spot_finder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spot_finders/edit.html.erb
<h1>Editing spot_finder</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot_finder %> |
<%= link_to 'Back', spot_finders_path %>

app/views/spot_finders/index.html.erb
<h1>Listing spot_finders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spot_finders.each do |spot_finder| %>
  <tr>
    <td><%= spot_finder.name %></td>
    <td><%= spot_finder.longitude %></td>
    <td><%= spot_finder.latitude %></td>
    <td><%= link_to 'Show', spot_finder %></td>
    <td><%= link_to 'Edit', edit_spot_finder_path(spot_finder) %></td>
    <td><%= link_to 'Destroy', spot_finder, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spot finder', new_spot_finder_path %>

app/views/spot_finders/new.html.erb
<h1>Find a Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spot_finders_path %>

app/views/spot_finders/show.html.erb
<p>
  <b> Searching the following location </b>
</p>

<p>
  <b>Name:</b>
  <%= @spot_finder.name %>
</p>

<p>
  <b>Longitude:</b>
  <%= @spot_finder.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @spot_finder.latitude %>
</p>


<br><br><br><br>

<% @spots = Spot.all %>

<% for spot in @spots %>
    (<%= spot_longitude = spot.longitude %> ,
    <%= spot_latitude = spot.latitude %>)
    <% if (spot_latitude - @spot_finder.latitude.to_f).abs < 5 && (spot_longitude - @spot_finder.longitude.to_f).abs < 5 %>
        <h2><%= link_to spot.name, spot %></h2>
    <% end %>
    <br>
<% end %>

app/views/spots/_form.html.erb
<%= form_for @spot do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/spots/edit.html.erb
<% title "Edit Spot" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @spot %> |
  <%= link_to "View All", spots_path %>
</p>

app/views/spots/index.html.erb
<p>
    <% title "Spots" %> <br>
</p>

<% for spot in @spots %>
  <div class="spot">
    <h2><%= link_to spot.name, spot %></h2>
    Files: <%= spot.paintings.size %> <br></br>
  </div>
<% end %>


<p><%= link_to "New Spot", new_spot_path %>  <%= link_to "Spot Finder", new_spot_finder_path %> </p>

app/views/spots/new.html.erb
<% title "New Spot" %>

<%= render 'form' %>

<p><%= link_to "Back to List", spots_path %></p>

app/views/spots/show.html.erb
<% title @spot.name %>


<div class="ContentFlow">
    <div class="loadIndicator"><div class="indicator"></div></div>
    <div class="flow">
      <% for painting in @spot.paintings %>
        <div class="item" href="../paintings/<%=painting.id%>">
            <% if painting.image_url.include? '.jpg' or painting.image_url.include?'.png'%>
                <%= image_tag(painting.image_url, :class => "content")%>

            <% elsif painting.image_url.include? '.doc' or painting.image_url.include? '.docx' %>
                <%= image_tag('word_icon.png', :class => "content")%>

            <% elsif painting.image_url.include? '.pdf' %>
                <%= image_tag('pdf_icon.png', :class => "content")%>

            <% else %>
                <%= image_tag('question_icon.png', :class => "content")%>
            <% end %>
            <div class="caption"><%=painting.name%></div>
        </div>
      <% end %>

    </div>
    <div class="globalCaption"></div>
    <div class="scrollbar"><div class="slider"><div class="position"></div></div></div>
</div>



<p>
  <%= link_to "Add a File", new_painting_path(:spot_id => @spot) %> |
  <%= link_to "Remove Spot", @spot, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View Spots", spots_path %>
</p>